### ISSUE TITLE
Test Engine - Definitions

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/TestCentric.Home#1]
I developed the idea of a TestEngine for NUnit beginning in 2007, when it was first presented to the Mono Gathering in Boston. It evolved over time and an implementation was created for NUnit 3.0. Some parts of the design were never implemented and eventually the team taking over development of the engine decided to go in a slightly different direction.

In this issue, I want to begin to lay out the needs I see for further engine development. This is the first step toward deciding whether to create a new TestCentric engine project or to continue working with the NUnit engine. It seems clear that we have to start with some notion of what is needed from the engine, so that's what I will attempt to do.

There has been some debate about the proper use of certain terms, including the term "engine" itself. For that reason, I'm starting out by defining terminology as I will use it. These definitions are not intended to be "better" than anybody else's definitions in any sense. They are simply descriptions of how I am using the words.

### Platforms

A platform is a combination of hardware, operating system and runtime framework on which our software needs to run. Each individual piece of software (runners, engine, framework, etc.) may need to run on a different set of platforms. The platforms we need to support tends to drive the design to a much greater extent than any other factors.

### Spaces

When talking about platfors, I think it helps to think about the two "spaces" in which test execution software has to operate. (This particular use of the word is my own, by the way.) Before discussing what platforms fall into each space, let's attempt to define them.

#### Development Space

As I intend the terms, **Development Space** is the platform on which a developer writes code, compiles it and launches tests. With NUnit, that space is generally limited to the Windows, Linux and IoS operating systems running on the desktop. (A developer writing a mobile application, for example, does not generally develop __on__ a mobile system.)

#### Test Execution Space

This space encompasses all the platforms and environments under which the software being developed will eventually run and therefore where the tests must be executed. This space is a superset of the development space, since we may need to run tests on the development platforms as well. I'll try to break this down further in the next section.

### Runners

**Runner** is a great example of a term that has been overloaded many times in many different ways. In this essay, I am using the term to mean a piece of software that interacts with the developer to allow selection of what tests to run and where and how to run them. (This definition, for example, excludes the various internal "XxxxxxxRunner" classes within the NUnit engine.)

By definition, a **Runner** needs to exist in the **Development Space** only.

### Test Engine

As used here, the term **Test Engine**, refers to common functionality needed by all or most **Runners**, extracted into a library so that test discovery and execution may be done in a standard way without duplication of effort.

Like the **Runner**, a **Test Engine** does not need to exist outside of **Development Space**. Any functionality needed in both spaces (Development and Test Execution) needs to be extracted from the engine.

### Test Agents

A test Agent is responsible for actually discovering tests and executing them. As such, it needs to run in **Test Execution Space**. Since that space is a superset of **Development Space** a version or versions need to exist that will run in **Development Space** as well.

### Test Framework

A **Test Framework** is able to discover and execute tests written against a specific API on a specific platform. For example, the NUnit 3 framework allows running tests against the NUnit 3 API.

A **Test Agent** may be designed to deal with a particular framework or may support multiple frameworks through an API.

### Conclusions?

I could draw some conclusions here WRT how these definitions might impact the design of a future Test Engine and, in fact, I have some ideas of my own already. But this seems like a good place to pause for comments and to see if anyone else is ready to offer ideas or conclusions. :smile:

**Comment by CharliePoole** [comment]
@TestCentric/gui-team @TestCentric/contributors Looking for feedback please!

**Comment by CharliePoole** [comment]
Moving along... the key question is this...

Precisely what platforms should we support in **Developer Space** ?

This relates to the engine itself, its agents and any runners that use it, at least at this point. It's possible that the engine might eventually become a service. If that happens, then a runner targeting, for example, .NET 2.0 could use a service that targeted .NET Core 3.0. However, for the moment, the two are tied together because the engine is loaded into the process of the runner.

For the moment, I'm excluding agents because they have some different issues. I'll treat them in a separate comment.

#### .NET Framework

One of the targets of the NUnit Test Engine is .NET 2.0. This allows it to be used by any runner that targets .NET 2.0 or higher. The NUnit 3 Console runner targets .NET 2.0. The current version of the TestCentric Gui targets .NET 4.5.

At the present time, I don't think many developers are limited to use of .NET 2.0 on their machines! So that's an easy decision. What's harder is to determine the precise minimum version of the .NET Framework that we should support. I'd say that 4.5 is the lowest we ought to consider, but 4.6.2 or 4.7.2 are also possible choices right now. @TestCentric/gui-team I'm looking for comments on this.

Eventually, or if we select a high enough minimum version, we may be able to use .NET Core only for the engine. But for now it seems as if some level of .NET Framework is needed.

#### .NET Core

Note that I call out the .NET Core platform here rather than some level of .NET Standard. That's because the engine is intended to be self-hosting eventually, that is, it is potentially an application rather than a library and needs to run on some platform.

This is one of the primary points on which my current views differ from the direction the NUnit Engine team has taken. Because I don't think the engine needs to run on a lot of platforms __and__ because I see it as an application, I lean towards .NET Core support rather than .NET Standard.

My thinking is that the platform would eventually become .NET Core 3.0, but that 2.0 is a good place to start right now. Once that's running, I would favor setting up an experimental 3.0 build using VS2019.

Comments?

**Comment by CharliePoole** [comment]
What about **Agents**?

An **Agent** is a piece of software that hosts test execution in a particular place or environment. For example, NUnit has two "process agents" that can run tests under .NET 2.0 or highter, in a 64-vit or 32-bit process.

The **Agent** concept is, however, more general than that. Agents can be used to run tests on other machines, in AppDomains, on mobile devices, and so forth. In NUnit, the concept was not expanded. Instead, it was decided to develop separate Engine builds for each environment.

Since an agent is an executable, it needs to be duplicated for every platform we want to target. However, an agent has much less to do than a fully formed engine and much of the code can be placed in a library, using .the lowest level of .NET standar possible for the actions to be performed.

@TestCentric/gui-team Comments so far?

**Comment by immeraufdemhund** [comment]
I can't speak to all any team other than the one I'm a part of now but we've tried working with .net core a few times over the months and just can't seem to make the switch and as such we are limited to using .net framework. I agree with going to .NET core as more people need access rather than an old soon to be outdated (IMO) framework. I'm personally worried that updating to .net 4.6+ would be a problem for those who use it in containers or on windows 7 dev machines.

**Comment by mikkelbu** [comment]
This will be a short answer as I'm pressed for time at the moment.

> Precisely what platforms should we support in Developer Space ?

I think that for Development Space we should support 4.5.2, as this is the lowest version of the .NET framework that is still supported (if we disregard .NET 3.5, see e.g. https://en.wikipedia.org/wiki/Template:.NET_Framework_version_history). I think going for .NET Core is too early, as a lot of people/projects/companies are still on the .NET framework.

> What about Agents?

If the differences between the agents for different platforms are so minimal, as it is the case now, then I don't see any problem with supporting many platforms.

**Comment by CharliePoole** [comment]
I've done a major spike, splitting the current NUnit engine into two parts, upper and lower. I kept the name engine for the upper and used engine.core for the lower for the time being. A good name would be useful here if anyone can think of one.

I have that build running locally, with one issue. The ExtensionService needs a to be revised so it looks for extension points in both new assemblies. We need an entry point in the API that allows the runner to designate what assemblies will be examined for extension points.

Since this is spike code, it's intended to be thrown away once we're ready to do an actual implementation.

**Comment by immeraufdemhund** [comment]
How about a mixture of all the words so that no one gets left out 🤣 
Honestly though I can't think of any one particular word that stands out as more correct then another.

**Comment by CharliePoole** [comment]
@immeraufdemhund I don't see that the words need to be self-explanatory, although they should make some kind of sense. I do think they need to have a clear definition spelled out.

We do have a some pretty clear statements that distinguish the engine from the other two major layers. That has lead to the notion (in NUnit) that the full engine needs to be built for all possible platforms.

I'm going to do a document and submit a PR on this pretty soon btw.

**Comment by immeraufdemhund** [comment]
we have Runners and Engines... makes me think that someone forgot to get in the car before they started it and so they are running after the car... maybe we should call it a Driver  🤣

in all seriousness though yes I agree on needing a clear definition. Helps tons when someone needs help in a subject and they don't have to type out "there is a bug in the engine/runner/driver/gui/window thingy"
